# Sample file specifies sample names and names of files containing sample reads
# Format: Tab-delimited, three columns
# sample_name  read1_file  [read2_file]
# if paired end, all samples must be paired end
# if single end, all samples must be single end
# If using Bhatt Lab workflows, sample file is also outputted
# at the end of the preprocessing workflow as
# preprocessing/01_processing/classification_input.txt
sample_file: /path/to/sample/file

# In which directory should results be outputted?
outdir: /path/to/output/directory

# Specifications for Kraken2
confidence_threshold: 0.1 # increase to reduce false positives for Kraken2
# minimum 0.0 (default for Kraken2), maximum 1.0
# see: https://github.com/DerrickWood/kraken2/blob/master/docs/MANUAL.markdown#confidence-scoring
database: /path/to/kraken/db
# are the read files gzipped?
gzipped: True # True or False

# Specifications for filtering Kraken2 reports prior to running Bracken
# what fraction of a viral genome should be covered to consider it a true positive?
cov_thresh_viral: 0.10
# how many unique minimizers should be covered in a viral genome ""?
minimizer_thresh_viral: 0
# same for bacterial
cov_thresh_bacterial: 0.01
minimizer_thresh_bacterial: 0

# Specifications for Bracken
read_length: 150 # if you change this, make sure you have an appropriate Bracken database built for this read length
taxonomic_level: 'S' # which taxonomic level should reads be distributed to (for Bracken)? Currently can only be 'S' (species)
filter_thresh: 10 # do not assign reads to species with < this number of reads assigned by Kraken2
